// RANDOTODO compare child long jumpslash range with adult short
DEFINE_ENEMY_DISTANCE(ED_CLOSE)
// hammer or kokiri sword
DEFINE_ENEMY_DISTANCE(ED_SHORT_JUMPSLASH)
DEFINE_ENEMY_DISTANCE(ED_MASTER_SWORD_JUMPSLASH)
// sticks or BGS
DEFINE_ENEMY_DISTANCE(ED_LONG_JUMPSLASH)
DEFINE_ENEMY_DISTANCE(ED_BOMB_THROW)
DEFINE_ENEMY_DISTANCE(ED_BOOMERANG)
DEFINE_ENEMY_DISTANCE(ED_HOOKSHOT)
DEFINE_ENEMY_DISTANCE(ED_LONGSHOT)
DEFINE_ENEMY_DISTANCE(ED_FAR)