#ifndef DEFINE_RANDO_OPTIONS

#ifndef RANDO_OPTIONS_H
#define RANDO_OPTIONS_H
// Generic Settings (any binary option can use this)
//  off/on
typedef enum {
    RO_GENERIC_OFF,
    RO_GENERIC_ON,
} RandoOptionGenericOffOn;

// no/yes
typedef enum {
    RO_GENERIC_NO,
    RO_GENERIC_YES,
} RandoOptionGenericNoYes;

// don't skip/skip
typedef enum {
    RO_GENERIC_DONT_SKIP,
    RO_GENERIC_SKIP,
} RandoOptionGenericSkip;

// Closed Forest settings (On, Deku Only, Off)
typedef enum {
    RO_CLOSED_FOREST_ON,
    RO_CLOSED_FOREST_DEKU_ONLY,
    RO_CLOSED_FOREST_OFF,
} RandoOptionForest;

// Door of Time settings (closed, song only, open)
typedef enum {
    RO_DOOROFTIME_CLOSED,
    RO_DOOROFTIME_SONGONLY,
    RO_DOOROFTIME_OPEN,
} RandoOptionDoorOfTime;

// Zora's Fountain settings (closed, closed as child, open)
typedef enum {
    RO_ZF_CLOSED,
    RO_ZF_CLOSED_CHILD,
    RO_ZF_OPEN,
} RandoOptionZorasFountain;

// Sleeping Waterfall settings (closed, open)
typedef enum {
    RO_WATERFALL_CLOSED,
    RO_WATERFALL_OPEN,
} RandoOptionSleepingWaterfall;

// Jabu-Jabu settings (closed, open)
typedef enum {
    RO_JABU_CLOSED,
    RO_JABU_OPEN,
} RandoOptionJabu;

// Starting Age settings (child, adult, random)
typedef enum {
    RO_AGE_CHILD,
    RO_AGE_ADULT,
    RO_AGE_RANDOM,
} RandoOptionStartingAge;

// Fortress Carpenters settings (normal, fast, free)
typedef enum {
    RO_GF_CARPENTERS_NORMAL,
    RO_GF_CARPENTERS_FAST,
    RO_GF_CARPENTERS_FREE,
} RandoOptionGerudoFortress;

// Kakariko Gate settings (closed/open)
typedef enum {
    RO_KAK_GATE_CLOSED,
    RO_KAK_GATE_OPEN,
} RandoOptionKakarikoGate;

// Rainbow Bridge settings (vanilla, always open, stones, medallions, dungeon rewards, dungeons, Tokens)
typedef enum {
    RO_BRIDGE_VANILLA = 0,
    RO_BRIDGE_ALWAYS_OPEN,
    RO_BRIDGE_STONES,
    RO_BRIDGE_MEDALLIONS,
    RO_BRIDGE_DUNGEON_REWARDS,
    RO_BRIDGE_DUNGEONS,
    RO_BRIDGE_TOKENS,
    RO_BRIDGE_GREG,
} RandoOptionRainbowBridge;

// Bridge Reward Options settings (Standard rewards, Greg as reward, Greg as wildcard)
typedef enum {
    RO_BRIDGE_STANDARD_REWARD,
    RO_BRIDGE_GREG_REWARD,
    RO_BRIDGE_WILDCARD_REWARD,
} RandoOptionBridgeRewards;

// Shopsanity settings (off, specific count, random)
typedef enum {
    RO_SHOPSANITY_OFF,
    RO_SHOPSANITY_SPECIFIC_COUNT,
    RO_SHOPSANITY_RANDOM,
} RandoOptionShopsanity;

// Shopsanity count settings (0-7 items)
typedef enum {
    RO_SHOPSANITY_COUNT_ZERO_ITEMS,
    RO_SHOPSANITY_COUNT_ONE_ITEM,
    RO_SHOPSANITY_COUNT_TWO_ITEMS,
    RO_SHOPSANITY_COUNT_THREE_ITEMS,
    RO_SHOPSANITY_COUNT_FOUR_ITEMS,
    RO_SHOPSANITY_COUNT_FIVE_ITEMS,
    RO_SHOPSANITY_COUNT_SIX_ITEMS,
    RO_SHOPSANITY_COUNT_SEVEN_ITEMS,
    RO_SHOPSANITY_COUNT_EIGHT_ITEMS,
} RandoOptionShopsanityCount;

// Shopsanity price ranges
typedef enum {
    RO_PRICE_VANILLA,
    RO_PRICE_CHEAP_BALANCED, // Balanced random from 0-95, favoring lower numbers
    RO_PRICE_BALANCED,       // Random from 0-300, favoring lower numbers
    RO_PRICE_FIXED,
    RO_PRICE_RANGE,
    RO_PRICE_SET_BY_WALLET,
} RandoOptionPrices;

// Scrubsanity settings (off, affordable, expensive, random)
typedef enum {
    RO_SCRUBS_OFF,
    RO_SCRUBS_ONE_TIME_ONLY,
    RO_SCRUBS_ALL,
} RandoOptionScrubsanity;

// Ammo drop settings (on, "on+bombchu", off)
typedef enum {
    RO_AMMO_DROPS_OFF,
    // RO_AMMO_DROPS_ON_PLUS_BOMBCHU,
    RO_AMMO_DROPS_ON,
} RandoOptionAmmoDrops;

typedef enum {
    RO_BOSS_SOULS_OFF,
    RO_BOSS_SOULS_ON,
    RO_BOSS_SOULS_ON_PLUS_GANON,
} RandoOptionBossSouls;

// Fishsanity settings (off, loach only, pond only, grottos only, both)
typedef enum {
    RO_FISHSANITY_OFF,
    RO_FISHSANITY_HYRULE_LOACH,
    RO_FISHSANITY_POND,
    RO_FISHSANITY_OVERWORLD,
    RO_FISHSANITY_BOTH
} RandoOptionsFishsanity;

// Infinite Upgrades settings (off, progressive, condensed progressive)
typedef enum {
    RO_INF_UPGRADES_OFF,
    RO_INF_UPGRADES_PROGRESSIVE,
    RO_INF_UPGRADES_CONDENSED_PROGRESSIVE,
} RandoOptionInfiniteUpgrades;

// Any Dungeon Item (start with, vanilla, own dungeon, any dungeon,
// overworld, anywhere)
typedef enum {
    RO_DUNGEON_ITEM_LOC_STARTWITH,
    RO_DUNGEON_ITEM_LOC_VANILLA,
    RO_DUNGEON_ITEM_LOC_OWN_DUNGEON,
    RO_DUNGEON_ITEM_LOC_ANY_DUNGEON,
    RO_DUNGEON_ITEM_LOC_OVERWORLD,
    RO_DUNGEON_ITEM_LOC_ANYWHERE,
} RandoOptionDungeonItemLocation;

// Dungeon reward settings
typedef enum {
    RO_DUNGEON_REWARDS_VANILLA,
    RO_DUNGEON_REWARDS_END_OF_DUNGEON,
    RO_DUNGEON_REWARDS_ANY_DUNGEON,
    RO_DUNGEON_REWARDS_OVERWORLD,
    RO_DUNGEON_REWARDS_ANYWHERE,
} RandoOptionDungeonRewards;

// Keyring Settings
typedef enum {
    RO_KEYRINGS_OFF,
    RO_KEYRINGS_RANDOM,
    RO_KEYRINGS_COUNT,
    RO_KEYRINGS_SELECTION,
} RandoOptionKeyrings;

typedef enum {
    RO_KEYRING_FOR_DUNGEON_OFF,
    RO_KEYRING_FOR_DUNGEON_RANDOM,
    RO_KEYRING_FOR_DUNGEON_ON,
} RandoOptionKeyringForDungeon;

// Ganon's Boss Key Settings (vanilla, own dungeon, start with,
// overworld, anywhere, 100 GS reward)
typedef enum {
    RO_GANON_BOSS_KEY_VANILLA,
    RO_GANON_BOSS_KEY_OWN_DUNGEON,
    RO_GANON_BOSS_KEY_STARTWITH,
    RO_GANON_BOSS_KEY_ANY_DUNGEON,
    RO_GANON_BOSS_KEY_OVERWORLD,
    RO_GANON_BOSS_KEY_ANYWHERE,
    RO_GANON_BOSS_KEY_LACS_VANILLA,
    RO_GANON_BOSS_KEY_LACS_STONES,
    RO_GANON_BOSS_KEY_LACS_MEDALLIONS,
    RO_GANON_BOSS_KEY_LACS_REWARDS,
    RO_GANON_BOSS_KEY_LACS_DUNGEONS,
    RO_GANON_BOSS_KEY_LACS_TOKENS,
    RO_GANON_BOSS_KEY_KAK_TOKENS,
} RandoOptionGanonsBossKey;

typedef enum {
    RO_LACS_VANILLA,
    RO_LACS_STONES,
    RO_LACS_MEDALLIONS,
    RO_LACS_REWARDS,
    RO_LACS_DUNGEONS,
    RO_LACS_TOKENS,
} RandoOptionLACSCondition;

// LACS Reward Options settings (Standard rewards, Greg as reward, Greg as wildcard)
typedef enum {
    RO_LACS_STANDARD_REWARD,
    RO_LACS_GREG_REWARD,
    RO_LACS_WILDCARD_REWARD,
} RandoOptionLACSRewards;

// Ganon's Trials
typedef enum {
    RO_GANONS_TRIALS_SKIP,
    RO_GANONS_TRIALS_SET_NUMBER,
    RO_GANONS_TRIALS_RANDOM_NUMBER,
} RandoOptionGanonsTrials;

// Shuffle Dungeon Entrance Settings (Off, on, plus ganon)
typedef enum {
    RO_DUNGEON_ENTRANCE_SHUFFLE_OFF,
    RO_DUNGEON_ENTRANCE_SHUFFLE_ON,
    RO_DUNGEON_ENTRANCE_SHUFFLE_ON_PLUS_GANON,
} RandoOptionDungeonEntranceShuffle;

// Shuffle Boss Room Entrance Settings (Off, Age Restricted, Full)
typedef enum {
    RO_BOSS_ROOM_ENTRANCE_SHUFFLE_OFF,
    RO_BOSS_ROOM_ENTRANCE_SHUFFLE_AGE_RESTRICTED,
    RO_BOSS_ROOM_ENTRANCE_SHUFFLE_FULL,
} RandoOptionBossRoomEntranceShuffle;

// Shuffle Interior Entrance Settings (Off, simple, all)
typedef enum {
    RO_INTERIOR_ENTRANCE_SHUFFLE_OFF,
    RO_INTERIOR_ENTRANCE_SHUFFLE_SIMPLE,
    RO_INTERIOR_ENTRANCE_SHUFFLE_ALL,
} RandoOptionInteriorEntranceShuffle;

// Song shuffle Settings (Song locations, Dungeon rewards, anywhere)
typedef enum {
    RO_SONG_SHUFFLE_SONG_LOCATIONS,
    RO_SONG_SHUFFLE_DUNGEON_REWARDS,
    RO_SONG_SHUFFLE_ANYWHERE,
} RandoOptionSongShuffle;

// Shuffle Merchants Settings (Off, Beans Only, All but Beans, All)
typedef enum {
    RO_SHUFFLE_MERCHANTS_OFF,
    RO_SHUFFLE_MERCHANTS_BEANS_ONLY,
    RO_SHUFFLE_MERCHANTS_ALL_BUT_BEANS,
    RO_SHUFFLE_MERCHANTS_ALL
} RandoOptionShuffleMerchants;

// Starting Ocarina Settings (off, fairy)
typedef enum {
    RO_STARTING_OCARINA_OFF,
    RO_STARTING_OCARINA_FAIRY,
    RO_STARTING_OCARINA_TIME,
} RandoOptionStartingOcarina;

// Item Pool Settings
typedef enum {
    RO_ITEM_POOL_PLENTIFUL,
    RO_ITEM_POOL_BALANCED,
    RO_ITEM_POOL_SCARCE,
    RO_ITEM_POOL_MINIMAL,
} RandoOptionItemPool;

// Ice Trap Settings
typedef enum {
    RO_ICE_TRAPS_OFF,
    RO_ICE_TRAPS_NORMAL,
    RO_ICE_TRAPS_EXTRA,
    RO_ICE_TRAPS_MAYHEM,
    RO_ICE_TRAPS_ONSLAUGHT,
} RandoOptionIceTraps;

// Gossip Stone Hint Settings (no hints, needs nothing,
// needs mask of truth, needs stone of agony)
typedef enum {
    RO_GOSSIP_STONES_NONE,
    RO_GOSSIP_STONES_NEED_NOTHING,
    RO_GOSSIP_STONES_NEED_TRUTH,
    RO_GOSSIP_STONES_NEED_STONE,
} RandoOptionGossipStones;

// Hint Clarity Settings (obscure, ambiguous, clear)
typedef enum {
    RO_HINT_CLARITY_OBSCURE,
    RO_HINT_CLARITY_AMBIGUOUS,
    RO_HINT_CLARITY_CLEAR,
} RandoOptionHintClarity;

// Hint Distribution Settings (useless, balanced, strong, very strong)
typedef enum {
    RO_HINT_DIST_USELESS,
    RO_HINT_DIST_BALANCED,
    RO_HINT_DIST_STRONG,
    RO_HINT_DIST_VERY_STRONG,
} RandoOptionHintDistribution;

// Gerudo Fortress Key Settings (vanilla, any dungeon, overworld,
// anywhere)
typedef enum {
    RO_GERUDO_KEYS_VANILLA,
    RO_GERUDO_KEYS_ANY_DUNGEON,
    RO_GERUDO_KEYS_OVERWORLD,
    RO_GERUDO_KEYS_ANYWHERE,
} RandoOptionGerudoKeys;

// Tokensanity settings (off, dungeons, overworld, all)
typedef enum {
    RO_TOKENSANITY_OFF,
    RO_TOKENSANITY_DUNGEONS,
    RO_TOKENSANITY_OVERWORLD,
    RO_TOKENSANITY_ALL,
} RandoOptionTokensanity;

// Freestanding Hearts/Rupees settings (off, dungeons, overworld, all)
typedef enum {
    RO_SHUFFLE_FREESTANDING_OFF,
    RO_SHUFFLE_FREESTANDING_DUNGEONS,
    RO_SHUFFLE_FREESTANDING_OVERWORLD,
    RO_SHUFFLE_FREESTANDING_ALL,
} RandoOptionFreestanding;

// Shuffle Pots settings (off, dungeons, overworld, all)
typedef enum {
    RO_SHUFFLE_POTS_OFF,
    RO_SHUFFLE_POTS_DUNGEONS,
    RO_SHUFFLE_POTS_OVERWORLD,
    RO_SHUFFLE_POTS_ALL,
} RandoOptionShufflePots;

// Shuffle Grass settings (off, dungeons, overworld, all)
typedef enum {
    RO_SHUFFLE_GRASS_OFF,
    RO_SHUFFLE_GRASS_DUNGEONS,
    RO_SHUFFLE_GRASS_OVERWORLD,
    RO_SHUFFLE_GRASS_ALL,
} RandoOptionShuffleGrass;

// Shuffle Crates settings (off, dungeons, overworld, all)
typedef enum {
    RO_SHUFFLE_CRATES_OFF,
    RO_SHUFFLE_CRATES_DUNGEONS,
    RO_SHUFFLE_CRATES_OVERWORLD,
    RO_SHUFFLE_CRATES_ALL,
} RandoOptionShuffleCrates;

// Link's Pocket Settings (dungeon reward, advancement, anything, nothing)
typedef enum {
    RO_LINKS_POCKET_DUNGEON_REWARD,
    RO_LINKS_POCKET_ADVANCEMENT,
    RO_LINKS_POCKET_ANYTHING,
    RO_LINKS_POCKET_NOTHING,
} RandoOptionLinksPocket;

// Logic (glitchless/no logic)
typedef enum {
    RO_LOGIC_GLITCHLESS,
    RO_LOGIC_NO_LOGIC,
    RO_LOGIC_VANILLA,
} RandoOptionLogic;

// Damage Multiplier
typedef enum {
    RO_DAMAGE_MULTIPLIER_HALF,
    RO_DAMAGE_MULTIPLIER_DEFAULT,
    RO_DAMAGE_MULTIPLIER_DOUBLE,
    RO_DAMAGE_MULTIPLIER_QUADRUPLE,
    RO_DAMAGE_MULTIPLIER_OCTUPLE,
    RO_DAMAGE_MULTIPLIER_SEXDECUPLE,
    RO_DAMAGE_MULTIPLIER_OHKO,
} RandoOptionDamageMultiplier;

// MQ Dungeons
typedef enum {
    RO_MQ_DUNGEONS_NONE,
    RO_MQ_DUNGEONS_SET_NUMBER,
    RO_MQ_DUNGEONS_RANDOM_NUMBER,
    RO_MQ_DUNGEONS_SELECTION,
} RandoOptionMQDungeons;

typedef enum {
    RO_LOCATION_INCLUDE,
    RO_LOCATION_EXCLUDE,
} RandoOptionLocationInclusion;

typedef enum {
    RO_CHEST_GAME_OFF,
    RO_CHEST_GAME_SINGLE_KEYS,
    RO_CHEST_GAME_PACK,
} RandoOptionChestGame;

typedef enum {
    RO_MQ_SET_VANILLA,
    RO_MQ_SET_MQ,
    RO_MQ_SET_RANDOM,
} RandoOptionMQSet;

#endif // RANDO_OPTIONS_H

#else // DEFINE_RANDO_OPTIONS

// clang-format off
{ "RO_GENERIC_OFF", RO_GENERIC_OFF },
{ "RO_GENERIC_ON", RO_GENERIC_ON },
{ "RO_GENERIC_NO", RO_GENERIC_NO },
{ "RO_GENERIC_YES", RO_GENERIC_YES },
{ "RO_GENERIC_DONT_SKIP", RO_GENERIC_DONT_SKIP },
{ "RO_GENERIC_SKIP", RO_GENERIC_SKIP },
{ "RO_CLOSED_FOREST_ON", RO_CLOSED_FOREST_ON },
{ "RO_CLOSED_FOREST_DEKU_ONLY", RO_CLOSED_FOREST_DEKU_ONLY },
{ "RO_CLOSED_FOREST_OFF", RO_CLOSED_FOREST_OFF },
{ "RO_DOOROFTIME_CLOSED", RO_DOOROFTIME_CLOSED },
{ "RO_DOOROFTIME_SONGONLY", RO_DOOROFTIME_SONGONLY },
{ "RO_DOOROFTIME_OPEN", RO_DOOROFTIME_OPEN },
{ "RO_ZF_CLOSED", RO_ZF_CLOSED },
{ "RO_ZF_CLOSED_CHILD", RO_ZF_CLOSED_CHILD },
{ "RO_ZF_OPEN", RO_ZF_OPEN },
{ "RO_WATERFALL_CLOSED", RO_WATERFALL_CLOSED },
{ "RO_WATERFALL_OPEN", RO_WATERFALL_OPEN },
{ "RO_AGE_CHILD", RO_AGE_CHILD },
{ "RO_AGE_ADULT", RO_AGE_ADULT },
{ "RO_AGE_RANDOM", RO_AGE_RANDOM },
{ "RO_GF_CARPENTERS_NORMAL", RO_GF_CARPENTERS_NORMAL },
{ "RO_GF_CARPENTERS_FAST", RO_GF_CARPENTERS_FAST },
{ "RO_GF_CARPENTERS_FREE", RO_GF_CARPENTERS_FREE },
{ "RO_KAK_GATE_CLOSED", RO_KAK_GATE_CLOSED },
{ "RO_KAK_GATE_OPEN", RO_KAK_GATE_OPEN },
{ "RO_BRIDGE_VANILLA", RO_BRIDGE_VANILLA },
{ "RO_BRIDGE_ALWAYS_OPEN", RO_BRIDGE_ALWAYS_OPEN },
{ "RO_BRIDGE_STONES", RO_BRIDGE_STONES },
{ "RO_BRIDGE_MEDALLIONS", RO_BRIDGE_MEDALLIONS },
{ "RO_BRIDGE_DUNGEON_REWARDS", RO_BRIDGE_DUNGEON_REWARDS },
{ "RO_BRIDGE_DUNGEONS", RO_BRIDGE_DUNGEONS },
{ "RO_BRIDGE_TOKENS", RO_BRIDGE_TOKENS },
{ "RO_BRIDGE_GREG", RO_BRIDGE_GREG },
{ "RO_BRIDGE_STANDARD_REWARD", RO_BRIDGE_STANDARD_REWARD },
{ "RO_BRIDGE_GREG_REWARD", RO_BRIDGE_GREG_REWARD },
{ "RO_BRIDGE_WILDCARD_REWARD", RO_BRIDGE_WILDCARD_REWARD },
{ "RO_SHOPSANITY_OFF", RO_SHOPSANITY_OFF },
{ "RO_SHOPSANITY_SPECIFIC_COUNT", RO_SHOPSANITY_SPECIFIC_COUNT },
{ "RO_SHOPSANITY_RANDOM", RO_SHOPSANITY_RANDOM },
{ "RO_SHOPSANITY_COUNT_ZERO_ITEMS", RO_SHOPSANITY_COUNT_ZERO_ITEMS },
{ "RO_SHOPSANITY_COUNT_ONE_ITEM", RO_SHOPSANITY_COUNT_ONE_ITEM },
{ "RO_SHOPSANITY_COUNT_TWO_ITEMS", RO_SHOPSANITY_COUNT_TWO_ITEMS },
{ "RO_SHOPSANITY_COUNT_THREE_ITEMS", RO_SHOPSANITY_COUNT_THREE_ITEMS },
{ "RO_SHOPSANITY_COUNT_FOUR_ITEMS", RO_SHOPSANITY_COUNT_FOUR_ITEMS },
{ "RO_SHOPSANITY_COUNT_FIVE_ITEMS", RO_SHOPSANITY_COUNT_FIVE_ITEMS },
{ "RO_SHOPSANITY_COUNT_SIX_ITEMS", RO_SHOPSANITY_COUNT_SIX_ITEMS },
{ "RO_SHOPSANITY_COUNT_SEVEN_ITEMS", RO_SHOPSANITY_COUNT_SEVEN_ITEMS },
{ "RO_SHOPSANITY_COUNT_EIGHT_ITEMS", RO_SHOPSANITY_COUNT_EIGHT_ITEMS },
{ "RO_PRICE_VANILLA", RO_PRICE_VANILLA },
{ "RO_PRICE_CHEAP_BALANCED", RO_PRICE_CHEAP_BALANCED },
{ "RO_PRICE_BALANCED", RO_PRICE_BALANCED },
{ "RO_PRICE_FIXED", RO_PRICE_FIXED },
{ "RO_PRICE_RANGE", RO_PRICE_RANGE },
{ "RO_PRICE_SET_BY_WALLET", RO_PRICE_SET_BY_WALLET },
{ "RO_SCRUBS_OFF", RO_SCRUBS_OFF },
{ "RO_SCRUBS_ONE_TIME_ONLY", RO_SCRUBS_ONE_TIME_ONLY },
{ "RO_SCRUBS_ALL", RO_SCRUBS_ALL },
{ "RO_AMMO_DROPS_OFF", RO_AMMO_DROPS_OFF },
{ "RO_AMMO_DROPS_ON", RO_AMMO_DROPS_ON },
{ "RO_BOSS_SOULS_OFF", RO_BOSS_SOULS_OFF },
{ "RO_BOSS_SOULS_ON", RO_BOSS_SOULS_ON },
{ "RO_BOSS_SOULS_ON_PLUS_GANON", RO_BOSS_SOULS_ON_PLUS_GANON },
{ "RO_FISHSANITY_OFF", RO_FISHSANITY_OFF },
{ "RO_FISHSANITY_HYRULE_LOACH", RO_FISHSANITY_HYRULE_LOACH },
{ "RO_FISHSANITY_POND", RO_FISHSANITY_POND },
{ "RO_FISHSANITY_OVERWORLD", RO_FISHSANITY_OVERWORLD },
{ "RO_FISHSANITY_BOTH", RO_FISHSANITY_BOTH },
{ "RO_INF_UPGRADES_OFF", RO_INF_UPGRADES_OFF },
{ "RO_INF_UPGRADES_PROGRESSIVE", RO_INF_UPGRADES_PROGRESSIVE },
{ "RO_INF_UPGRADES_CONDENSED_PROGRESSIVE", RO_INF_UPGRADES_CONDENSED_PROGRESSIVE },
{ "RO_DUNGEON_ITEM_LOC_STARTWITH", RO_DUNGEON_ITEM_LOC_STARTWITH },
{ "RO_DUNGEON_ITEM_LOC_VANILLA", RO_DUNGEON_ITEM_LOC_VANILLA },
{ "RO_DUNGEON_ITEM_LOC_OWN_DUNGEON", RO_DUNGEON_ITEM_LOC_OWN_DUNGEON },
{ "RO_DUNGEON_ITEM_LOC_ANY_DUNGEON", RO_DUNGEON_ITEM_LOC_ANY_DUNGEON },
{ "RO_DUNGEON_ITEM_LOC_OVERWORLD", RO_DUNGEON_ITEM_LOC_OVERWORLD },
{ "RO_DUNGEON_ITEM_LOC_ANYWHERE", RO_DUNGEON_ITEM_LOC_ANYWHERE },
{ "RO_DUNGEON_REWARDS_VANILLA", RO_DUNGEON_REWARDS_VANILLA },
{ "RO_DUNGEON_REWARDS_END_OF_DUNGEON", RO_DUNGEON_REWARDS_END_OF_DUNGEON },
{ "RO_DUNGEON_REWARDS_ANY_DUNGEON", RO_DUNGEON_REWARDS_ANY_DUNGEON },
{ "RO_DUNGEON_REWARDS_OVERWORLD", RO_DUNGEON_REWARDS_OVERWORLD },
{ "RO_DUNGEON_REWARDS_ANYWHERE", RO_DUNGEON_REWARDS_ANYWHERE },
{ "RO_KEYRINGS_OFF", RO_KEYRINGS_OFF },
{ "RO_KEYRINGS_RANDOM", RO_KEYRINGS_RANDOM },
{ "RO_KEYRINGS_COUNT", RO_KEYRINGS_COUNT },
{ "RO_KEYRINGS_SELECTION", RO_KEYRINGS_SELECTION },
{ "RO_KEYRING_FOR_DUNGEON_OFF", RO_KEYRING_FOR_DUNGEON_OFF },
{ "RO_KEYRING_FOR_DUNGEON_RANDOM", RO_KEYRING_FOR_DUNGEON_RANDOM },
{ "RO_KEYRING_FOR_DUNGEON_ON", RO_KEYRING_FOR_DUNGEON_ON },
{ "RO_GANON_BOSS_KEY_VANILLA", RO_GANON_BOSS_KEY_VANILLA },
{ "RO_GANON_BOSS_KEY_OWN_DUNGEON", RO_GANON_BOSS_KEY_OWN_DUNGEON },
{ "RO_GANON_BOSS_KEY_STARTWITH", RO_GANON_BOSS_KEY_STARTWITH },
{ "RO_GANON_BOSS_KEY_ANY_DUNGEON", RO_GANON_BOSS_KEY_ANY_DUNGEON },
{ "RO_GANON_BOSS_KEY_OVERWORLD", RO_GANON_BOSS_KEY_OVERWORLD },
{ "RO_GANON_BOSS_KEY_ANYWHERE", RO_GANON_BOSS_KEY_ANYWHERE },
{ "RO_GANON_BOSS_KEY_LACS_VANILLA", RO_GANON_BOSS_KEY_LACS_VANILLA },
{ "RO_GANON_BOSS_KEY_LACS_STONES", RO_GANON_BOSS_KEY_LACS_STONES },
{ "RO_GANON_BOSS_KEY_LACS_MEDALLIONS", RO_GANON_BOSS_KEY_LACS_MEDALLIONS },
{ "RO_GANON_BOSS_KEY_LACS_REWARDS", RO_GANON_BOSS_KEY_LACS_REWARDS },
{ "RO_GANON_BOSS_KEY_LACS_DUNGEONS", RO_GANON_BOSS_KEY_LACS_DUNGEONS },
{ "RO_GANON_BOSS_KEY_LACS_TOKENS", RO_GANON_BOSS_KEY_LACS_TOKENS },
{ "RO_GANON_BOSS_KEY_KAK_TOKENS", RO_GANON_BOSS_KEY_KAK_TOKENS },
{ "RO_LACS_VANILLA", RO_LACS_VANILLA },
{ "RO_LACS_STONES", RO_LACS_STONES },
{ "RO_LACS_MEDALLIONS", RO_LACS_MEDALLIONS },
{ "RO_LACS_REWARDS", RO_LACS_REWARDS },
{ "RO_LACS_DUNGEONS", RO_LACS_DUNGEONS },
{ "RO_LACS_TOKENS", RO_LACS_TOKENS },
{ "RO_LACS_STANDARD_REWARD", RO_LACS_STANDARD_REWARD },
{ "RO_LACS_GREG_REWARD", RO_LACS_GREG_REWARD },
{ "RO_LACS_WILDCARD_REWARD", RO_LACS_WILDCARD_REWARD },
{ "RO_GANONS_TRIALS_SKIP", RO_GANONS_TRIALS_SKIP },
{ "RO_GANONS_TRIALS_SET_NUMBER", RO_GANONS_TRIALS_SET_NUMBER },
{ "RO_GANONS_TRIALS_RANDOM_NUMBER", RO_GANONS_TRIALS_RANDOM_NUMBER },
{ "RO_DUNGEON_ENTRANCE_SHUFFLE_OFF", RO_DUNGEON_ENTRANCE_SHUFFLE_OFF },
{ "RO_DUNGEON_ENTRANCE_SHUFFLE_ON", RO_DUNGEON_ENTRANCE_SHUFFLE_ON },
{ "RO_DUNGEON_ENTRANCE_SHUFFLE_ON_PLUS_GANON", RO_DUNGEON_ENTRANCE_SHUFFLE_ON_PLUS_GANON },
{ "RO_BOSS_ROOM_ENTRANCE_SHUFFLE_OFF", RO_BOSS_ROOM_ENTRANCE_SHUFFLE_OFF },
{ "RO_BOSS_ROOM_ENTRANCE_SHUFFLE_AGE_RESTRICTED", RO_BOSS_ROOM_ENTRANCE_SHUFFLE_AGE_RESTRICTED },
{ "RO_BOSS_ROOM_ENTRANCE_SHUFFLE_FULL", RO_BOSS_ROOM_ENTRANCE_SHUFFLE_FULL },
{ "RO_INTERIOR_ENTRANCE_SHUFFLE_OFF", RO_INTERIOR_ENTRANCE_SHUFFLE_OFF },
{ "RO_INTERIOR_ENTRANCE_SHUFFLE_SIMPLE", RO_INTERIOR_ENTRANCE_SHUFFLE_SIMPLE },
{ "RO_INTERIOR_ENTRANCE_SHUFFLE_ALL", RO_INTERIOR_ENTRANCE_SHUFFLE_ALL },
{ "RO_SONG_SHUFFLE_SONG_LOCATIONS", RO_SONG_SHUFFLE_SONG_LOCATIONS },
{ "RO_SONG_SHUFFLE_DUNGEON_REWARDS", RO_SONG_SHUFFLE_DUNGEON_REWARDS },
{ "RO_SONG_SHUFFLE_ANYWHERE", RO_SONG_SHUFFLE_ANYWHERE },
{ "RO_SHUFFLE_MERCHANTS_OFF", RO_SHUFFLE_MERCHANTS_OFF },
{ "RO_SHUFFLE_MERCHANTS_BEANS_ONLY", RO_SHUFFLE_MERCHANTS_BEANS_ONLY },
{ "RO_SHUFFLE_MERCHANTS_ALL_BUT_BEANS", RO_SHUFFLE_MERCHANTS_ALL_BUT_BEANS },
{ "RO_SHUFFLE_MERCHANTS_ALL", RO_SHUFFLE_MERCHANTS_ALL },
{ "RO_STARTING_OCARINA_OFF", RO_STARTING_OCARINA_OFF },
{ "RO_STARTING_OCARINA_FAIRY", RO_STARTING_OCARINA_FAIRY },
{ "RO_STARTING_OCARINA_TIME", RO_STARTING_OCARINA_TIME },
{ "RO_ITEM_POOL_PLENTIFUL", RO_ITEM_POOL_PLENTIFUL },
{ "RO_ITEM_POOL_BALANCED", RO_ITEM_POOL_BALANCED },
{ "RO_ITEM_POOL_SCARCE", RO_ITEM_POOL_SCARCE },
{ "RO_ITEM_POOL_MINIMAL", RO_ITEM_POOL_MINIMAL },
{ "RO_ICE_TRAPS_OFF", RO_ICE_TRAPS_OFF },
{ "RO_ICE_TRAPS_NORMAL", RO_ICE_TRAPS_NORMAL },
{ "RO_ICE_TRAPS_EXTRA", RO_ICE_TRAPS_EXTRA },
{ "RO_ICE_TRAPS_MAYHEM", RO_ICE_TRAPS_MAYHEM },
{ "RO_ICE_TRAPS_ONSLAUGHT", RO_ICE_TRAPS_ONSLAUGHT },
{ "RO_GOSSIP_STONES_NONE", RO_GOSSIP_STONES_NONE },
{ "RO_GOSSIP_STONES_NEED_NOTHING", RO_GOSSIP_STONES_NEED_NOTHING },
{ "RO_GOSSIP_STONES_NEED_TRUTH", RO_GOSSIP_STONES_NEED_TRUTH },
{ "RO_GOSSIP_STONES_NEED_STONE", RO_GOSSIP_STONES_NEED_STONE },
{ "RO_HINT_CLARITY_OBSCURE", RO_HINT_CLARITY_OBSCURE },
{ "RO_HINT_CLARITY_AMBIGUOUS", RO_HINT_CLARITY_AMBIGUOUS },
{ "RO_HINT_CLARITY_CLEAR", RO_HINT_CLARITY_CLEAR },
{ "RO_HINT_DIST_USELESS", RO_HINT_DIST_USELESS },
{ "RO_HINT_DIST_BALANCED", RO_HINT_DIST_BALANCED },
{ "RO_HINT_DIST_STRONG", RO_HINT_DIST_STRONG },
{ "RO_HINT_DIST_VERY_STRONG", RO_HINT_DIST_VERY_STRONG },
{ "RO_GERUDO_KEYS_VANILLA", RO_GERUDO_KEYS_VANILLA },
{ "RO_GERUDO_KEYS_ANY_DUNGEON", RO_GERUDO_KEYS_ANY_DUNGEON },
{ "RO_GERUDO_KEYS_OVERWORLD", RO_GERUDO_KEYS_OVERWORLD },
{ "RO_GERUDO_KEYS_ANYWHERE", RO_GERUDO_KEYS_ANYWHERE },
{ "RO_TOKENSANITY_OFF", RO_TOKENSANITY_OFF },
{ "RO_TOKENSANITY_DUNGEONS", RO_TOKENSANITY_DUNGEONS },
{ "RO_TOKENSANITY_OVERWORLD", RO_TOKENSANITY_OVERWORLD },
{ "RO_TOKENSANITY_ALL", RO_TOKENSANITY_ALL },
{ "RO_SHUFFLE_FREESTANDING_OFF", RO_SHUFFLE_FREESTANDING_OFF },
{ "RO_SHUFFLE_FREESTANDING_DUNGEONS", RO_SHUFFLE_FREESTANDING_DUNGEONS },
{ "RO_SHUFFLE_FREESTANDING_OVERWORLD", RO_SHUFFLE_FREESTANDING_OVERWORLD },
{ "RO_SHUFFLE_FREESTANDING_ALL", RO_SHUFFLE_FREESTANDING_ALL },
{ "RO_SHUFFLE_POTS_OFF", RO_SHUFFLE_POTS_OFF },
{ "RO_SHUFFLE_POTS_DUNGEONS", RO_SHUFFLE_POTS_DUNGEONS },
{ "RO_SHUFFLE_POTS_OVERWORLD", RO_SHUFFLE_POTS_OVERWORLD },
{ "RO_SHUFFLE_POTS_ALL", RO_SHUFFLE_POTS_ALL },
{ "RO_SHUFFLE_GRASS_OFF", RO_SHUFFLE_GRASS_OFF },
{ "RO_SHUFFLE_GRASS_DUNGEONS", RO_SHUFFLE_GRASS_DUNGEONS },
{ "RO_SHUFFLE_GRASS_OVERWORLD", RO_SHUFFLE_GRASS_OVERWORLD },
{ "RO_SHUFFLE_GRASS_ALL", RO_SHUFFLE_GRASS_ALL },
{ "RO_SHUFFLE_CRATES_OFF", RO_SHUFFLE_CRATES_OFF },
{ "RO_SHUFFLE_CRATES_DUNGEONS", RO_SHUFFLE_CRATES_DUNGEONS },
{ "RO_SHUFFLE_CRATES_OVERWORLD", RO_SHUFFLE_CRATES_OVERWORLD },
{ "RO_SHUFFLE_CRATES_ALL", RO_SHUFFLE_CRATES_ALL },
{ "RO_LINKS_POCKET_DUNGEON_REWARD", RO_LINKS_POCKET_DUNGEON_REWARD },
{ "RO_LINKS_POCKET_ADVANCEMENT", RO_LINKS_POCKET_ADVANCEMENT },
{ "RO_LINKS_POCKET_ANYTHING", RO_LINKS_POCKET_ANYTHING },
{ "RO_LINKS_POCKET_NOTHING", RO_LINKS_POCKET_NOTHING },
{ "RO_LOGIC_GLITCHLESS", RO_LOGIC_GLITCHLESS },
{ "RO_LOGIC_NO_LOGIC", RO_LOGIC_NO_LOGIC },
{ "RO_LOGIC_VANILLA", RO_LOGIC_VANILLA },
{ "RO_DAMAGE_MULTIPLIER_HALF", RO_DAMAGE_MULTIPLIER_HALF },
{ "RO_DAMAGE_MULTIPLIER_DEFAULT", RO_DAMAGE_MULTIPLIER_DEFAULT },
{ "RO_DAMAGE_MULTIPLIER_DOUBLE", RO_DAMAGE_MULTIPLIER_DOUBLE },
{ "RO_DAMAGE_MULTIPLIER_QUADRUPLE", RO_DAMAGE_MULTIPLIER_QUADRUPLE },
{ "RO_DAMAGE_MULTIPLIER_OCTUPLE", RO_DAMAGE_MULTIPLIER_OCTUPLE },
{ "RO_DAMAGE_MULTIPLIER_SEXDECUPLE", RO_DAMAGE_MULTIPLIER_SEXDECUPLE },
{ "RO_DAMAGE_MULTIPLIER_OHKO", RO_DAMAGE_MULTIPLIER_OHKO },
{ "RO_MQ_DUNGEONS_NONE", RO_MQ_DUNGEONS_NONE },
{ "RO_MQ_DUNGEONS_SET_NUMBER", RO_MQ_DUNGEONS_SET_NUMBER },
{ "RO_MQ_DUNGEONS_RANDOM_NUMBER", RO_MQ_DUNGEONS_RANDOM_NUMBER },
{ "RO_MQ_DUNGEONS_SELECTION", RO_MQ_DUNGEONS_SELECTION },
{ "RO_LOCATION_INCLUDE", RO_LOCATION_INCLUDE },
{ "RO_LOCATION_EXCLUDE", RO_LOCATION_EXCLUDE },
{ "RO_CHEST_GAME_OFF", RO_CHEST_GAME_OFF },
{ "RO_CHEST_GAME_SINGLE_KEYS", RO_CHEST_GAME_SINGLE_KEYS },
{ "RO_CHEST_GAME_PACK", RO_CHEST_GAME_PACK },
{ "RO_MQ_SET_VANILLA", RO_MQ_SET_VANILLA },
{ "RO_MQ_SET_MQ", RO_MQ_SET_MQ },
{ "RO_MQ_SET_RANDOM", RO_MQ_SET_RANDOM },
// clang-format on

#endif
